version: '3'
services:
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
  ecom-app:
    build : 
      context: .
      dockerfile: Dockerfile
      args:
        - ENV_FILE=.env
    ports:
      - 3000:5000